server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: USUARIO-SERVICE
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/api/usuario/**
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/** #,/otra-ruta/**
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio
        - id: CALIFICACION-SERVICE
          uri: lb://CALIFICACION-SERVICE
          predicates:
            - Path=/api/calificacion/**
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/