server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: USUARIO-SERVICE
          uri: lb://USUARIO-SERVICE
          predicates:
            - Path=/usuario/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**
        - id: CALIFICACION-SERVICE
          uri: lb://CALIFICACION-SERVICE
          predicates:
            - Path=/calificacion/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/