server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario-service
    username: root
    password:
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: usuario-service

eureka:
  instance:
    prefer-ip-address: true # Para que el servicio se registre con la IP en lugar del nombre del host
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
    level:
        com.mcsv.usuario_service: DEBUG