server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: calificacion-service

  application:
    name: calificacion-service

  config:
    import: configserver:http://localhost:8085 # Config Server URL
  profiles:
    active: prod # Profile

logging:
  level:
    com.mcsv.calificacion_service: DEBUG
