server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: producto-service

  application:
    name: producto-service

logging:
  level:
    root: INFO
    com.mcsv.producto_service: DEBUG
  file:
    name: logs/producto-service.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ #aqui va el username y password de eureka
