global:
  scrape_interval: 10s # Tiempo de espera entre cada scrape
  evaluation_interval: 10s # Tiempo de espera entre cada evaluación

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.18.148:8081']
        labels:
          application: 'Producto-Service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.18.148:8082' ]
        labels:
          application: 'Order-Service'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.18.148:8085' ]
        labels:
          application: 'Notification-Service'

  - job_name: 'inventario-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.18.148:8083' ]
        labels:
          application: 'Inventario-Service'