server:
  port: 8083

spring:
  application:
    name: inventario-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventario-service
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.mcsv.inventario_service: DEBUG
  file:
    name: logs/inventario-service.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ #aqui va el username y password de eureka

management:
  tracing:
    sampling:
      probability: 1.0