server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.mcsv.order_service: DEBUG
  file:
    name: logs/order-service.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ #aqui va el username y password de eureka

resilience4j:
  circuitbreaker:
    instances:
      llamadaInventario:
        registerHealthIndicator: true # Indicar el estado del circuit breaker
        event-consumer-buffer-size: 10 # Tamaño del buffer de eventos
        failure-rate-threshold: 50 # Porcentaje de fallos
        minimum-number-of-calls: 5 # Minima cantidad de llamadas
        sliding-window-size: 10 # Maxima cantidad de repeticiones
        sliding-window-type: COUNT_BASED # Tipo de ventana
        automatic-transition-from-open-to-half-open-enabled: true # Transición automática de abierto a semiabierto
        wait-duration-in-open-state:
          seconds: 6 # Tiempo de espera en estado abierto
        permitted-number-of-calls-in-half-open-state: 3 # Cantidad de llamadas permitidas en estado semiabierto

  retry:
    instances:
      llamadaInventario:
        max-attempts: 3 # Cantidad de reintentos
        wait-duration: 5s # Tiempo de espera entre reintentos

