server:
  port: 8084

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/ordencompra/** # Usa el nombre del servicio registrado en Eureka
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio

        - id: INVENTARIO-SERVICE
          uri: lb://INVENTARIO-SERVICE
          predicates:
            - Path=/api/inventario/** # Usa el nombre del servicio registrado en Eureka
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio

        - id: PRODUCTO-SERVICE
          uri: lb://PRODUCTO-SERVICE
          predicates:
            - Path=/api/producto/** # Usa el nombre del servicio registrado en Eureka
          filters:
            - StripPrefix=1  # Esto elimina el prefijo /api/ antes de la solicitud al servicio

  # Punto de entrada para los cliente
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/mcsv

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/ #aqui va el username y password de eureka

logging:
  level:
    com.mcsv.api_gateway: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO

management:
  tracing:
    sampling:
      probability: 1.0